# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0ae0b504c80d69e9e93ad2d8a39f416c3d4d2063ad397cb134951029bf01cb4286f700eba3d517a9df8aa46353ba31c9d1631265d582fb0d5127d90e2411f5b

test:
  secret_key_base: 9f70016e0475ee165ecfeaf367cd51ec4f8fcf881a9b1722e3b65f21f75a73970ece5e2630d66df2c1c6e14722638319680ac9bac55f612f694ba82d5d11319c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
