# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d05879b66f4e9a782412214f6ebd4112627d2ba199c632b2658d1d5078b4483dddf737a58f41c89c9d0f05a5b63aff74cd7941a1582103c5800612fefbd1769b

test:
  secret_key_base: 57ec6adff1ef7f92ee84d6f7a259c245bcba45e183f74018c50eefaa5f29453f059f0906ff81dfacf9167e196a9fc47db28f8678ac0bc30f6660f0506459fa5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
