# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe81a90535d819642bc40540610eadb6af7c1de27c1d68a5951f93133476243be1e93c189650fda0c0fd7fae0734822d30221395dba5c05dbf289da18ae21073

test:
  secret_key_base: f12f288eb566dbdb2b3aa1856e254686d3d7a5d6461425d77129b58920a6abfffa8ce3b925444f1552c64cdd8eb1d61657bef78b41593909a493e8f02455f425

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
